### PR TITLE
feature/output styles

### PR DESCRIPTION
**Pull request by builtbywill**
Summary of Changes
* fix `latexifyArray` to correctly loop through style `properties`. there was a bug where the properties array was sliced during recursions, and this caused future atoms from never ouputting certain styles since they were lost along the way
* update `latexifyArray` logic to not output "default" styles (autoFontFamily, "normal" weight and size, etc.). also just cleanup logic a bit.
* fix `toLatex` to _never_ output styles inside of variable names
* fix `applyStyle` method to clear `baseFontFamily` when clearing `fontFamily`
* fix styles keyboard to use the correct style prop names, and fix the call to the `$applyStyles` method (which was broken) and have call the public method which includes validation and can toggle the "current" style for future typing, not just the "selection"s style

### CODE REVIEW

**Comment by builtbywill** [comment]
FYI If you checkout this branch you can open `mathlive/examples/basic/index.html` in your browser to test out the changes and see the styles virtual keyboard

**Comment by tragessere** [comment]
@builtbywill  I've been testing this here and in Variate and noticed there was some strange behavior when you type inside of a styled region of text. In the demo here, the new text gets excluded from the styling e.g. typing 'B' in the middle of the styled 'AC' here. Is there a way to include that in the text?

Using this in Variate additionally pushes the cursor all the way to the end of the input, but that doesn't seem to be a problem with the repo here.

image

image

**Comment by builtbywill** [comment]
@tragessere I'm not having an issue typing inside of an existing style (see recording) 🤔 

https://github.com/purdue-tlt/mathlive/assets/689209/10343a36-f56e-4c4b-9ecc-5e90decd7483

I do see the bug over in Variate about getting kicked to the end. I'm guessing that is related to the forced re-render / re-selection setting logic. I will take a look.

**Comment by tragessere** [comment]
@builtbywill Seems like it only happens when you type in the style manually and not from the keyboard, though I'm not sure how that would happen.


https://github.com/purdue-tlt/mathlive/assets/6559092/6da41cb4-162b-415f-b356-c6c6ebb54e7c

**Comment by builtbywill** [comment]
@tragessere okay I think I found the issue by looking at the differences in the mathlist atoms

image

the typed command is setting `baseFontFamily` while the keyboard is setting `fontFamily`

I will figure out where that needs to change and let you know once it's fixed

**Comment by builtbywill** [comment]
@tragessere okay I fixed the baseFontFamily/fontFamily issue, please take a look

**Comment by tragessere** [comment]
@builtbywill It's working great now, thanks for the fix!

**Review by tragessere — APPROVED** [review]

**Review by lily514 — APPROVED** [review]

**Pull request merged**
